import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <nav className="flex justify-between items-center z-50 gap-4 h-20 w-full bg-sky-500 text-white sticky top-0 left-0 px-4">
          <h1 className="text-3xl font-bold"> Sharifi Programming Academy</h1>
          <ul className="flex justify-between items-center gap-3">
            <li><Link href='/home'>Home</Link></li>
            <li><Link href='/products'>Products</Link></li>
            <li><Link href='/about'>About</Link></li>
            <li><Link href='/contact'>contact</Link></li>
          </ul>
        </nav>
        {children}
        <footer className="w-full p-5 flex justify-center items-center text-white bg-sky-500">
          <p className="text-center">&copy;Sharifi Programming Academy @2025</p>
        </footer>
      </body>
    </html>
  );
}
