import type { Metadata } from "next";
import "../globals.css";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {/* <Image src="/about.jpg" height={100} width={1400} alt="" /> */}
        <div className="flex justify-between gap-4 w-[70%] mx-auto p-4">
        </div>
        {children}
      </body>
    </html>
  );
}
