import type { Metadata } from "next";
import "../globals.css";
import Image from "next/image";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,profile,posts,notification
}: Readonly<{
  children: React.ReactNode;
  profile: React.ReactNode;
  posts: React.ReactNode;
  notification: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Image src="/hero.jpg" height={100} width={1400} alt="" />
        <div className="flex justify-between gap-4 w-[70%] mx-auto p-4">
          {profile}
          {posts}
          {notification}
        </div>
        {children}
      </body>
    </html>
  );
}
